TARGET_COLUMN: Close+1
DATA_PATH: data/AMRT.csv
DATA_PATH_2 : data/ihsg.csv

scoring:
- neg_root_mean_squared_error
- r2
n_iter_search: 3
verbosity: 2
cv: 5
random_state: 123

X_PATH_TRAIN: output/X_train.pkl
Y_PATH_TRAIN: output/y_train.pkl
X_PATH_VALID: output/X_valid.pkl
Y_PATH_VALID: output/y_valid.pkl
X_PATH_TEST: output/X_test.pkl
Y_PATH_TEST: output/y_test.pkl
DUMP_TRAIN: output/preprocess_data/data/preprocessed_x_train_v1.1.pkl
DUMP_VALID: output/preprocess_data/data/preprocessed_x_valid_v1.1.pkl
DUMP_TEST: output/preprocess_data/data/preprocessed_x_test_v1.1.pkl
DUMP_PREDICT: output/predict/data/preprocessed_x_predict_v1.1.pkl
MODEL_NAME: output/model/train/model_name_v1.1.pkl
BEST_MODEL: output/model/train/best_estimator_v1.1.pkl
TRAIN_LOG: output/model/train/train_log_v1.1.pkl