TARGET_COLUMN: Close+1
DATA_PATH: data/AMRT.csv
DATA_PATH_2 : data/ihsg.csv

scoring: neg_root_mean_squared_error
n_iter_search: 3
verbosity: 2
cv: 5
random_state: 123

X_PATH_TRAIN: output/X_train.pkl
Y_PATH_TRAIN: output/y_train_final.pkl
X_PATH_VALID: output/X_valid.pkl
Y_PATH_VALID: output/y_valid_final.pkl
X_PATH_TEST: output/X_test.pkl
Y_PATH_TEST: output/y_test_final.pkl
DUMP_TRAIN: output/X_train_final.pkl
DUMP_VALID: output/X_valid_final.pkl
DUMP_TEST: output/X_test_final.pkl
DUMP_PREDICT: output/predict/data/preprocessed_x_predict_v1.1.pkl
BEST_NAME: output/best_name.pkl
MODEL_NAME: output/model_name.pkl
BEST_MODEL: output/best_estimator.pkl
TRAIN_LOG: output/model/train/train_log_v1.1.pkl
RESULT_TRAIN: output/result.pkl